name = "Jurodedu-Neoforged"
author = "Formuna"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97cd09377307bf54337d786567e6ad03a687ac70d3b41ad4a51a4e9195aa5070"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
